#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xDBD2CE893E2D1C87 (cfeck@kde.org)
#
Name     : kldap
Version  : 18.12.3
Release  : 6
URL      : https://download.kde.org/stable/applications/18.12.3/src/kldap-18.12.3.tar.xz
Source0  : https://download.kde.org/stable/applications/18.12.3/src/kldap-18.12.3.tar.xz
Source99 : https://download.kde.org/stable/applications/18.12.3/src/kldap-18.12.3.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
Requires: kldap-data = %{version}-%{release}
Requires: kldap-lib = %{version}-%{release}
Requires: kldap-license = %{version}-%{release}
Requires: kldap-locales = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules pkgconfig(libsasl2)
BuildRequires : openldap-dev

%description
# KLDAP #
Allows LDAP accessing with a convenient Qt style C++ API.

%package data
Summary: data components for the kldap package.
Group: Data

%description data
data components for the kldap package.


%package dev
Summary: dev components for the kldap package.
Group: Development
Requires: kldap-lib = %{version}-%{release}
Requires: kldap-data = %{version}-%{release}
Provides: kldap-devel = %{version}-%{release}

%description dev
dev components for the kldap package.


%package doc
Summary: doc components for the kldap package.
Group: Documentation

%description doc
doc components for the kldap package.


%package lib
Summary: lib components for the kldap package.
Group: Libraries
Requires: kldap-data = %{version}-%{release}
Requires: kldap-license = %{version}-%{release}

%description lib
lib components for the kldap package.


%package license
Summary: license components for the kldap package.
Group: Default

%description license
license components for the kldap package.


%package locales
Summary: locales components for the kldap package.
Group: Default

%description locales
locales components for the kldap package.


%prep
%setup -q -n kldap-18.12.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1552000666
mkdir -p clr-build
pushd clr-build
export LDFLAGS="${LDFLAGS} -fno-lto"
%cmake ..
make  %{?_smp_mflags} VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1552000666
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/kldap
cp COPYING.LIB %{buildroot}/usr/share/package-licenses/kldap/COPYING.LIB
pushd clr-build
%make_install
popd
%find_lang kio_ldap
%find_lang libkldap5

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/kservices5/ldap.protocol
/usr/share/kservices5/ldaps.protocol
/usr/share/xdg/kldap.categories
/usr/share/xdg/kldap.renamecategories

%files dev
%defattr(-,root,root,-)
/usr/include/KF5/KLDAP/KLDAP/Ber
/usr/include/KF5/KLDAP/KLDAP/LdapAttributeProxyModel
/usr/include/KF5/KLDAP/KLDAP/LdapConfigWidget
/usr/include/KF5/KLDAP/KLDAP/LdapConnection
/usr/include/KF5/KLDAP/KLDAP/LdapControl
/usr/include/KF5/KLDAP/KLDAP/LdapDN
/usr/include/KF5/KLDAP/KLDAP/LdapDefs
/usr/include/KF5/KLDAP/KLDAP/LdapModel
/usr/include/KF5/KLDAP/KLDAP/LdapObject
/usr/include/KF5/KLDAP/KLDAP/LdapOperation
/usr/include/KF5/KLDAP/KLDAP/LdapSearch
/usr/include/KF5/KLDAP/KLDAP/LdapServer
/usr/include/KF5/KLDAP/KLDAP/LdapStructureProxyModel
/usr/include/KF5/KLDAP/KLDAP/LdapUrl
/usr/include/KF5/KLDAP/KLDAP/Ldif
/usr/include/KF5/KLDAP/kldap/ber.h
/usr/include/KF5/KLDAP/kldap/kldap_export.h
/usr/include/KF5/KLDAP/kldap/ldapattributeproxymodel.h
/usr/include/KF5/KLDAP/kldap/ldapconfigwidget.h
/usr/include/KF5/KLDAP/kldap/ldapconnection.h
/usr/include/KF5/KLDAP/kldap/ldapcontrol.h
/usr/include/KF5/KLDAP/kldap/ldapdefs.h
/usr/include/KF5/KLDAP/kldap/ldapdn.h
/usr/include/KF5/KLDAP/kldap/ldapmodel.h
/usr/include/KF5/KLDAP/kldap/ldapobject.h
/usr/include/KF5/KLDAP/kldap/ldapoperation.h
/usr/include/KF5/KLDAP/kldap/ldapsearch.h
/usr/include/KF5/KLDAP/kldap/ldapserver.h
/usr/include/KF5/KLDAP/kldap/ldapstructureproxymodel.h
/usr/include/KF5/KLDAP/kldap/ldapurl.h
/usr/include/KF5/KLDAP/kldap/ldif.h
/usr/include/KF5/kldap_version.h
/usr/lib64/cmake/KF5Ldap/KF5LdapConfig.cmake
/usr/lib64/cmake/KF5Ldap/KF5LdapConfigVersion.cmake
/usr/lib64/cmake/KF5Ldap/KF5LdapTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF5Ldap/KF5LdapTargets.cmake
/usr/lib64/libKF5Ldap.so
/usr/lib64/qt5/mkspecs/modules/qt_Ldap.pri

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/HTML/ca/kioslave5/ldap/index.cache.bz2
/usr/share/doc/HTML/ca/kioslave5/ldap/index.docbook
/usr/share/doc/HTML/de/kioslave5/ldap/index.cache.bz2
/usr/share/doc/HTML/de/kioslave5/ldap/index.docbook
/usr/share/doc/HTML/en/kioslave5/ldap/index.cache.bz2
/usr/share/doc/HTML/en/kioslave5/ldap/index.docbook
/usr/share/doc/HTML/es/kioslave5/ldap/index.cache.bz2
/usr/share/doc/HTML/es/kioslave5/ldap/index.docbook
/usr/share/doc/HTML/et/kioslave5/ldap/index.cache.bz2
/usr/share/doc/HTML/et/kioslave5/ldap/index.docbook
/usr/share/doc/HTML/it/kioslave5/ldap/index.cache.bz2
/usr/share/doc/HTML/it/kioslave5/ldap/index.docbook
/usr/share/doc/HTML/nl/kioslave5/ldap/index.cache.bz2
/usr/share/doc/HTML/nl/kioslave5/ldap/index.docbook
/usr/share/doc/HTML/pt/kioslave5/ldap/index.cache.bz2
/usr/share/doc/HTML/pt/kioslave5/ldap/index.docbook
/usr/share/doc/HTML/pt_BR/kioslave5/ldap/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kioslave5/ldap/index.docbook
/usr/share/doc/HTML/ru/kioslave5/ldap/index.cache.bz2
/usr/share/doc/HTML/ru/kioslave5/ldap/index.docbook
/usr/share/doc/HTML/sr/kioslave5/ldap/index.cache.bz2
/usr/share/doc/HTML/sr/kioslave5/ldap/index.docbook
/usr/share/doc/HTML/sv/kioslave5/ldap/index.cache.bz2
/usr/share/doc/HTML/sv/kioslave5/ldap/index.docbook
/usr/share/doc/HTML/uk/kioslave5/ldap/index.cache.bz2
/usr/share/doc/HTML/uk/kioslave5/ldap/index.docbook

%files lib
%defattr(-,root,root,-)
/usr/lib64/libKF5Ldap.so.5
/usr/lib64/libKF5Ldap.so.5.10.3
/usr/lib64/qt5/plugins/kf5/kio/ldap.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/kldap/COPYING.LIB

%files locales -f kio_ldap.lang -f libkldap5.lang
%defattr(-,root,root,-)

